services:
  nginx-proxy:
    image: nginx:1.23.4
    container_name: nginx-proxy
    depends_on: 
      - orthanc
      - orthanc-auth-service
    restart: unless-stopped
    ports: 
      - 443:443
    volumes:
      - ./config/certs/orthweb.digihunch.com.pem:/usr/local/nginx/conf/site.pem:ro
      - ./config/nginx/:/etc/nginx/:ro

    environment:
      ENABLE_ORTHANC: "true"
      ENABLE_KEYCLOAK: "true"
      ENABLE_ORTHANC_TOKEN_SERVICE: "false"
      ENABLE_HTTPS: "false"

  # first setup through configuration file and build step
  orthanc:
    image: orthancteam/orthanc:24.2.0
    container_name: orthanc-backend # Path to the configuration files (stored as secrets)
    command: /etc/orthanc/
    volumes:
      - ./data/storage-orthanc:/var/lib/orthanc/data
      - ./config/orthanc/:/etc/orthanc/
    depends_on: 
      - orthanc-db
    restart: unless-stopped
    environment:
      VERBOSE_ENABLED: "true"
    secrets:
      - site.pem 
    healthcheck:
      disable: true 

  orthanc-auth-service:
    image: orthancteam/orthanc-auth-service:24.2.0
    # disable ports in prod or at least don't make this webservice public !
    ports: ["8000:8000"]
    restart: unless-stopped
    environment:
      SECRET_KEY: "my-secret-key"
      ENABLE_KEYCLOAK: "true"
      KEYCLOAK_URI: "http://keycloak:8080/realms/orthanc/"
      #PERMISSIONS_FILE_PATH: "path_to_the file"
      PUBLIC_ORTHANC_ROOT: "http://localhost/orthanc/"
      PUBLIC_LANDING_ROOT: "http://localhost/orthanc/ui/app/token-landing.html"
      USERS: |
        {
          "share-user": "share-password",
          "demo-script-user": "demo-script-password",
          "orthanc-oe2-user": "orthanc-oe2-password"
        }
        
  orthanc-db:
    image: postgres:17
    restart: unless-stopped
    container_name: orthanc-db
    shm_size: 128mb
    volumes: 
      - ./data/pgdata-orthanc:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "orthancdbpsw"
      POSTGRES_USER: "orthancdbusr"
      POSTGRES_DB: "orthancdb"

  keycloak:
    image: orthancteam/orthanc-keycloak:24.2.0
    depends_on: 
      - keycloak-db
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "change-me"
      KC_DB_URL: "jdbc:postgresql://keycloak-db:5432/keycloakdb"
      KC_DB_USERNAME: "keycloakdbusr"
      KC_DB_PASSWORD: "keycloakdbpsw"
      # 2 following lines to uncomment (and adapt) if HTTPS is enabled in nginx
      KC_HOSTNAME_URL: "https://orthweb.digihunch.com/keycloak"
      KC_HOSTNAME_ADMIN_URL: "https://orthweb.digihunch.com/keycloak"
    
  keycloak-db:
    image: postgres:17
    restart: unless-stopped
    container_name: keycloak-db
    shm_size: 128mb
    volumes: 
      - ./data/pgdata-keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "keycloakdbpsw"
      POSTGRES_USER: "keycloakdbusr"
      POSTGRES_DB: "keycloakdb"

secrets:
  site.pem:
    file: ./config/certs/orthweb.digihunch.com.pem 
